site_name: fluxbound
site_description: A minimalistic python package for flux balance analysis
site_author: Daniel Machado
repo_url: https://github.com/cdanielmachado/fluxbound

theme:
  name: material
  palette:
    primary: default
  features:
    - navigation.sections
    - navigation.top
    - search.suggest

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

nav:
  - Home: index.md
  - API: api.md